cmangos/mangos-classic

src/game/SpellEffects.cpp
This spell included the handful of snowflakes spell (45036) which was not present in Classic (introduced with 2.3.0).  As a result sometimes nothing happens when players use this event functionality.  This fix ensures players will either get mistletoe or fresh holly everytime not withstanding the usual cooldowns.
=> Classic Mistletoe Spell Fix

src/game/Unit.cpp
Confirmed by sniffs (but 2.3) and still valid in 6.x
=> Minimum speed rate is 0.01f

contrib/extractor/README.linux, contrib/mysql_to_pgsql/README
`cmake -i` is no longer supported and will give the error `The "cmake -i" wizard mode is no longer supported.` when used. I simply changed some build instructions to use `cmake .`
=> Changed "cmake -i" to "cmake ." in some build instructions

src/game/Object.cpp
Flightmaster NPCs should show quest icon and correct icon when you hover over them in client when having a quest.
=> Show quest icons at flightmaster npcs

src/game/SpellEffects.cpp
PVS-Studio warning: V547 Expression is always false. Probably the '||' operator should be used here. SpellEffects.cpp 2872
In the specified condition, the variable m_spellInfo->Id is verified against two different values at the same time. The result of this check is always false, of course. The author most likely made a mistake and instead of '||' operator used '&&'.
It should be noted that the program commented on strange code behavior, and perhaps, it was caused by this error exactly.
=> An error in the condition "Consecrated Weapon and Blessed Wizard Oil" duration

src/game/Spell.cpp
Looks like someone way back wrongly assumed that 1.12.1 needed dodge/miss/etc messages to be explicitly sent by the server, and their "fix" for this resulted in these messages showing up twice. Please verify & merge this change! (Or tell me if you find something wrong)
=> Fix duplicate dodge/miss/resist/evade/etc messages

src/game/SpellEffects.cpp, src/scriptdev2/scripts/eastern_kingdoms/blackwing_lair/boss_broodlord_lashlayer.cpp, src/scriptdev2/scripts/kalimdor/temple_of_ahnqiraj/boss_bug_trio.cpp
+ some versions of 'Knock Away' lower the target's threat by 50% (used by Molten Giants, Broodlord Razorgore and Vem)
+ assign correct spells to Broodlord Razorgore and Vem
=> Knock Away - Script Effect

src/game/SpellEffects.cpp
set hate towards target to zero (what a surprise...), Lava Annihilator will use this to swap targets after each successful melee hit
=> Hate to Zero

.gitignore, src/mangosd/CliRunnable.cpp
this fixes the hang until a keypress with 'Halting process...' when quitting mangosd (tested on ubuntu 16)
=> fix hang exiting mangosd on linux

src/game/Grids/GridNotifiers.h
Not enough things were considered CCs, and considering isCharmed a CC is
useless since we check if the mob is hostile to us first, which it will be if it's charmed, so we would never even get to this check.
=> Update what is considered CC by EventAI

doc/EventAI.txt, src/game/AI/EventAI/CreatureEventAI.cpp, src/game/AI/EventAI/CreatureEventAI.h, src/game/AI/EventAI/CreatureEventAIMgr.cpp
Allows NPCs to perform action only when facing the back or the front of their target in EventAI. This is typically useful for rogue-like NPCs.
=> Implement EVENT_T_FACING_TARGET

sql/updates/mangos/z2709_01_mangos_comments.sql
Table doesn't exist in mangos-classic DB and causes errors when `z2709_01_mangos_comments.sql` is executed.
=> Remove reference to prospecting_loot_template

src/game/Globals/ObjectMgr.cpp
NPC text locale strings were being erased in ObjectMgr::LoadQuestgiverGreeting due to a typo introduced in 8c09757.
This bug was spotted by @M2us.
=> Fix NPC text localization

cmake/macros/FindBoost/FindBoost.cmake
Resolves some issues with the newest boost library v1.65.1.
=> Update FindBoost.cmake to newest version.

src/game/Entities/GameObject.cpp, src/game/Entities/GameObject.h, src/game/Globals/SharedDefines.h, src/game/Spells/SpellEffects.cpp
Improve the way traps are handled when targetted by SPELL_EFFECT_OPEN_LOCK (like disarm trap spell). Instead of being desactivated and despawning, they change state and use an alternate visual for the duration of the open lock (which is equal to the GO respawn time). They are then rearmed (back to GO_STATE_READY)
This should fix:
- the disarming of Suppression Device traps in BWL that were despawning instead of being disarmed
- quests 4734 and 4735 in UBRS where egg traps were still triggering instead of temporary changing state as expected
=> Improve handle of SPELL_EFFECT_OPEN_LOCK for GAMEOBJECT_TYPE_TRAP

src/game/Entities/Unit.cpp
The current situation of setting both weapons to 100 ms when out of
range / don't have target in front can be abused (every time you get a hit in
with your slow main hand, run out of range or turn around and wait for
the error to display, triggered by your fast offhander; now both your
weapons are ready again since attack timers are set to 100ms on both...
Ref; https://github.com/elysium-project/server/issues/2655
=> Don't set attack timer on both weapons

src/mangosd/mangosd.conf.dist.in, src/realmd/realmd.conf.dist.in
No name resolution is being performed for name or string entered into the BindIP field.  Previous to this commit https://github.com/cmangos/mangos-classic/commit/ab2f3f6725a5ad979c4641a9a8268da9bc537227 BindIP was ignored.  Realmd and Mangosd would just bind to 0.0.0.0
This PR just updates the description of BindIP within the sample configs.
=> minor update to BindIP description in sample configs

src/game/Entities/GossipDef.cpp
Quests that don't require items use the RequestItemsText field to store the text that is shown when you talk to the quest giver while the quest is incomplete. Therefore the text should not be shown for them when the quest is complete. For quests that do require items, it is self explanatory.
Here is a gif to illustrate what i am talking about.
https://youtu.be/jTSyexUNN9E?t=5m20s
You can see that on retail, it goes straight to offering the reward. You should not have to click "continue".
=> Do not show incomplete quest text for completed quests.

src/game/AI/ScriptDevAI/scripts/kalimdor/onyxias_lair/boss_onyxia.cpp, src/game/AI/ScriptDevAI/scripts/kalimdor/ruins_of_ahnqiraj/boss_ossirian.cpp
Attempt at fixing Undefined behavior
variable is modified while being used twice between sequence points
Ref: https://medium.com/@Coder_HarryLee/checking-the-world-of-warcraft-cmangos-open-source-server-5405f364fb32
=> Scripts undefined behaviour

contrib/vmap_extractor/vmapextract/vmapexport.cpp
This statement would always be true.
This puts it in line and smiliar functionality with the statements already fixed at line 125 and 231 in MapTree.cpp
Ref: https://medium.com/@Coder_HarryLee/checking-the-world-of-warcraft-cmangos-open-source-server-5405f364fb32
the re-extracted resources are made temporarily available [here](https://www.dropbox.com/s/6hcxi94n5l6yovp/fixifResources.rar?dl=0)
=> Fix always true if statement

src/game/Entities/Player.cpp, src/game/Entities/Unit.cpp
Most assuredly guardians shouldn't be removed on creature death, so move that to player.
Do creatures even have minipets? they are only created through spelleffect EffectSummonCritter as far as I'm aware and are there any creature's which has a spell using that effect? I'm not so sure. 
Should creature's totems get removed on owner's death when pets shouldn't? I'd think not but really need a bit more research on that before moving it along with the others..
Solves cmangos/issues#1063 , also their AI persists through death, meaning they will keep using their abilities if set in eventai, which is awesome, they will however not really despawn as they just go back to 'following' their master's corpse, while they should despawn upon JustReachedHome() - they never do go home, though. Looking …
=> Fix creature's pets despawning on master death

src/game/Entities/Player.cpp, src/game/World/World.cpp, src/mangosd/mangosd.conf.dist.in, src/shared/SystemConfig.h
The reputation system rate on lower level quests and mobs is more complex than simply having 1 config value for gray levels, which doesn't make much sense.
> Just like XP, if the mob or quest level is 6 or more levels below you, the reputation gained will be lowered by 20% for each level (however it can't be lower than 20%). Completing quests or killing mobs whose level is higher than yours won't give you more reputation.
> 
> For example, completing a level 10 quest that normally gives 25 points will give: 
> 
> Level | Points
> 1 | 25 (100%)
> 10 | 25 (100%)
> 15 | 25 (100%)
> 16 | 20 (80%)
> 17 | 15 (60%)
> 18 | 10 (40%)
> 19 | 5 (20%)
> 60 | 5 (20%)
https://wowwiki.fandom.com/wiki/Reputation?oldid=346091#Gaining_and_Losing_reputation
This was changed in wotlk to not have any penalty …
=> Readjust reputation gain on lower level mobs/quests

contrib/git_id/CMakeLists.txt
The folder architecture stuff isn't needed and neither is the properties link flag since it'll fail linking on windows anyway
I based the inclusion on how recastdemomod is included but I should have based it on how extractors are included, which it is now
Ref: https://github.com/cmangos/mangos-tbc/commit/30a29c5593b2bf4e4d3c1dea86fd4dac3dd7a44c#commitcomment-32214692
I did test it underway and everything was working fine but I must have added the 
```
set_target_properties(git_id PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS")
```
after and forgot to delete cache and reload cmake.. It should be working as intended with this change.
=> CMakelist alterations for git_id

sql/base/mangos.sql
ERROR 1062 (23000) at line 8074: Duplicate entry '0-8-176' for key 'PRIMARY'
Doesn't require any sql update as it's only the base file which is affected, it is however preventing us from running the sql file.
It is only classic which has this error in the base file.
=> Fix base\mangos.sql

src/game/Entities/Pet.cpp, src/game/Entities/Unit.cpp
Autocast spells should be set to autocast by default when creatures are first summon/tamed
Touched up the same functionality for charmed units (they determined autocast spells in a really weird manner)
Proof; https://www.youtube.com/watch?v=ILsu79gPj00 (at 4:29)
Addresses the last issue remaining mentioned in https://github.com/cmangos/issues/issues/882
> the pet bar doesn't actually reflect what the default settings are properly. Waterbolt is set to autocast and Freeze is set to manual cast by default,
=> Set autocast default to enabled for pets

src/game/Spells/SpellEffects.cpp
for example if you execute :  
.cast 7975
you are making the server crash if you don't have this fix.
=> add a null ptr check when cast a SummonWild spell

src/game/AI/BaseAI/PetAI.cpp, src/game/Entities/PetHandler.cpp
Stored pet spells don't execute properly because the spell is never applied the targets properly, but autocast spells do, so move stored spells further down the code and handle it along with autocast spells
Active pet spells cast manually have the same issue
in pethandler we never set a target for the spell so looking for a target in the spell is silly, remove that, we need to also set the target of the spell before casting it or the pet will cast it on itself.
This solves 
https://github.com/cmangos/issues/issues/1036
and https://github.com/cmangos/issues/issues/870
=> Fix player-controlled pet spellcasting by manual casting

src/game/PlayerBot/Base/PlayerbotAI.cpp
Fix a segfault when we attempt to learn a spell from a trainer that doesn't teach that spell.
To reproduce:
- Create two bots of different classes 
- Target one of the class trainers (the ones below are the troll mage & priest trainers in Durotar) and instruct the bots to learn a class-specific spell that that trainer teaches, e.g. 
-- `/tar mai'ah`
-- `/p skill learn [Arcane Intellect]`
- Target the other class trainer and instruct the bots to learn the same spell, e.g. 
-- `/tar ken'jai`
-- `/p skill learn [Arcane Intellect]`
=> [Playerbot] Fix crash bug when training skills

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/stormwind_city.cpp
m_uiStartEventTimer & m_uiEndEventTimer related conditions in UpdateAI have a boundary logic problem. 
if m_uiStartEventTimer == uiDiff exactly at one server tick, then the m_uiStartEventTimer will result in a certain 0 value at the very next server tick. 
This will cause a rare false on the if (m_uiStartEventTimer) check at the beginning of UpdateAI() and lead to the related quest cannot start. 
So as the m_uiEndEventTimer will lead to a cannot end.
Maybe just accept quest 1447 and abort it while completed for several times. LOL
This issue just happened on some rare time. But it did happened and some players filed me about this. So I checked.
- None
=> Fix rare fail of npc_dashel_stonefistAI phase change.

sql/base/dbc/cmangos_fixes/Spell.sql, src/game/Chat/Chat.cpp, src/game/Chat/Chat.h, src/game/Chat/Level3.cpp
This adds .modify commands for all stats. It's a very nice feature to have when testing things, or even just for fun. And unlike the commands to modify hp and mana, these will not reset when you change items or are hit with an aura that changes your stats. Implemented using spells as requested by killerwife.
You can use this to clear all modifications:
> .reset mods
=> Implement modify commands for stats.

doc/script_commands.txt, sql/base/mangos.sql, src/game/Chat/Chat.cpp, src/game/DBScripts/ScriptMgr.cpp, src/game/Tools/Language.h
Table "db_script_string" was recently renamed to "dbscript_string", but there were a few remaining references to "db_script_string", causing a fresh installation to fail when importing mangos.sql.
- Fixes https://github.com/cmangos/issues/issues/2099
=> Renamed remaining db_script_string -> dbscript_string

src/game/AI/ScriptDevAI/scripts/world/npcs_special.cpp
Fixed issue [2074](https://github.com/cmangos/issues/issues/2226)
This is how patients looks like. They have owner now, and quest works correctly, they can even die!
Quest objectives reached! No Evade when casting the spell
Quest completed as usual, so let's try to finish it
First Aid skill before...
First Aid skill after
I haven't tried for Alliance, but as long as fix is not faction-specific it should work good
- fixes https://github.com/cmangos/issues/issues/2226
- Have First Aid skill topped near 225
- Visit faction-specific NPC to get this quest
- Take quest and start `healing` the soldiers, witness they are not evading your heals
- Be a good doc and heal 15 patients
- Complete the quest
=> Triage quest fix

src/game/Entities/Unit.cpp
SpellId was being inserted into the SMSG_SPELLDAMAGESHIELD packet in void Unit::DealMeleeDamage, making it the damage and the damage the School. I simply reverted that section to how it was in commit 2484c82. This only affected the combat log and the scrolling combat text, not the actual damage being done.
https://i.imgur.com/2hhsnJl.png
https://i.imgur.com/k91TOvb.png
https://i.imgur.com/splVxmr.jpg
- fixes #2235
1. Use spell or item with Apply Aura: Damage shield on Apply Area Aura: Damage shield
2. Get attacked
Confirm the packet structure for SMSG_SPELLDAMAGESHIELD, check in tbc and wotlk as well (seems that wotlk just needs the overkill added)
=> Fix Issue #2235: SMSG_SPELLDAMAGESHIELD sending incorrect values to set

src/game/Entities/Unit.cpp
While playing WoW locally, I noticed that hearthstone did not teleport pet correctly.  They become unresponsive, you can't dismiss them and pet appears only after logout. If distance is small, pet will try running to you, which does not look "natural". 
Captured few gifs so you can witness how fix works
- None. Decided to create PR straight away
1. Have class with pet as it's part (e.g. warlock/hunter)
2. Use hearthstone 
3. See that pet is teleport along with you
=> Hearthstone pet fix

src/game/AI/BaseAI/UnitAI.cpp, src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/stormwind_city.cpp, src/game/AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.cpp, src/game/AuctionHouseBot/AuctionHouseBot.cpp, src/game/Combat/ThreatManager.cpp
Ran classic core with Valgrind and discovered some out-of-bounds array access in AHBot as well as usage of uninitialized variables in other classes.
See commit comments for stacktraces from Valgrind.
- None
- None (or run classic core with `valgrind --track-origins=yes` before & after merging changes)
In Spell.cpp there is still an uninitialized variable being read, I did not dare touching this class. Here's the stacktrace from Valgrind:
```
Conditional jump or move depends on uninitialised value(s)
at 0x72FE9E: Spell::CheckTarget(Unit*, SpellEffectIndex, bool, CheckException) const (Spell.cpp:6149)
by 0x743A43: Spell::FillTargetMap() (Spell.cpp:532)
by 0x744EF1: Spell::cast(bool) (Spell.cpp:2841)
by 0x745845: Spell::SpellStart(SpellCastTargets const*, Aura*) (Spell.cpp:2592)
by 0x5AD963: …
```
=> Memory access fixes for AHBot and other classes

src/game/PlayerBot/AI/PlayerbotMageAI.cpp
The Playerbot mage AI will attempt to sheep elite mobs attacking it.
However the arcane magic immunity check is performed on the combat target, not on the attacking "target". This isn't necessarily the same.
- Add mage playerbot.
- Have mage attack a target immune to arcane magic.
- Have mage draw aggro from a beast.
- Mage will not try to sheep the beast, because his main target is immune to arcane magic.
=> Playerbot Mage AI: Fix Polymorph immunity check on wrong target

src/game/Chat/ChatHandler.cpp
Fixes two server crashing bugs when Playerbot is active.
- Form a group with bots.
- Leave the group.
- Type "/p .bot add x" although not in a group.
- Observe server crash due to NPE.
=> Playerbot: Fix 2 crash bugs

src/game/World/WorldState.cpp
I was unable to compile mangos under Fedora Linux with Ninja due to a missing GameEventMgr.h include in WorldState.cpp when configuring the build with
```bash
cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=mangos-classic-install -DDEBUG=0 -DBUILD_EXTRACTORS=ON -DPCH=OFF -S mangos-classic-source -B mangos-classic-build
```
Error was:
```cpp
[366/419] Building CXX object src/game/CMakeFiles/game.dir/World/WorldState.cpp.o
FAILED: src/game/CMakeFiles/game.dir/World/WorldState.cpp.o
/usr/bin/ccache /home/bogglez/bin/g++  -DBUILD_SCRIPTDEV -DDO_MYSQL -DDT_POLYREF64 -DMANGOS_DEBUG -DSYSCONFDIR=\"../etc/\" -D_DEBUG -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -I/home/bogglez/projects/mangos/mangos-classic-source/src/game …
```
=> Fix compilation of WorldState.cpp missing GameEventMgr.h

src/game/AI/BaseAI/UnitAI.cpp
Fixed issue [2247](https://github.com/cmangos/issues/issues/2247)
- fixes [#2247](https://github.com/cmangos/issues/issues/2247)
After server start, wait till the Crimson Courier and his bodyguards till e.g. Corin's Crossing and see there are no warnings if they cast Disarm on NPCs without the mainhand weapon.
=> Disarm warning fix

src/game/PlayerBot/AI/PlayerbotDruidAI.cpp, src/game/PlayerBot/AI/PlayerbotDruidAI.h, src/game/PlayerBot/AI/PlayerbotHunterAI.cpp, src/game/PlayerBot/AI/PlayerbotHunterAI.h, src/game/PlayerBot/AI/PlayerbotMageAI.cpp, src/game/PlayerBot/AI/PlayerbotMageAI.h, src/game/PlayerBot/AI/PlayerbotPaladinAI.cpp, src/game/PlayerBot/AI/PlayerbotPaladinAI.h, src/game/PlayerBot/AI/PlayerbotPriestAI.cpp, src/game/PlayerBot/AI/PlayerbotPriestAI.h, src/game/PlayerBot/AI/PlayerbotRogueAI.cpp, src/game/PlayerBot/AI/PlayerbotRogueAI.h, src/game/PlayerBot/AI/PlayerbotShamanAI.cpp, src/game/PlayerBot/AI/PlayerbotShamanAI.h, src/game/PlayerBot/AI/PlayerbotWarlockAI.cpp, src/game/PlayerBot/AI/PlayerbotWarlockAI.h, src/game/PlayerBot/AI/PlayerbotWarriorAI.cpp, src/game/PlayerBot/AI/PlayerbotWarriorAI.h, src/game/PlayerBot/Base/PlayerbotAI.cpp, src/game/PlayerBot/Base/PlayerbotAI.h, src/game/PlayerBot/Base/PlayerbotClassAI.cpp, src/game/PlayerBot/Base/PlayerbotClassAI.h, src/game/PlayerBot/Base/PlayerbotMgr.cpp
I found the Playerbot code to be difficult to comprehend, because it uses nullable parameters everywhere.
In this PR I changed manager, master, bot, and ai from nullable pointers to references. This makes dead code and redundantly defensive programming obvious (code like `if (!always_set_pointer) return ERROR` or `if (always_set_pointer && f())`.
The code repeats itself a lot, therefore the changes in this PR are unfortunately many, but follow a fixed pattern. They were mostly performed using regex patterns. Mostly `a->b` had to be changed to `a.b`, and tautologies were removed (`if (!m_ai) return ERROR)` etc).
In a future PR I intend to do the same with targets, but didn't want to make this PR too big. I have already noticed a couple of bugs that I intend to submit fixes for thanks to …
=> Feature cleanup playerbot nullable args

src/game/Spells/SpellAuras.cpp
aura is initialized as a nullptr and only gets assigned with a real object inside of an if function, that could also fail, but then a method of the Aura class is called without a guard, which can (and apparently does) lead to the server trying to execute a method from a nullptr, which should be an access violation
- None
- possibly related to https://github.com/cmangos/issues/issues/2513
- None
=> SpellAura guard against nullptr access

src/game/BattleGround/BattleGroundHandler.cpp, src/game/BattleGround/BattleGroundMgr.cpp
- Fix: empty BG scores
- Fix: BG queue is not updated when player joins queue
Note:  To fix score list I compared cmangos-classic with mangos_zero + vmangos.
Note:  To fix BG queue I compared mangos-classic with mangos-tbc/wotlk
Note:  Rank fix is from vmangos
BG Queue - https://github.com/cmangos/mangos-tbc/blob/4098a6ca19bee27f808a85565ee5b2915bbced48/src/game/BattleGround/BattleGroundHandler.cpp#L219
Scores - https://github.com/vmangos/core/blob/ca6dd2f02dc7cf24b38a4e55db1c3ec34b8fea6c/src/game/Battlegrounds/BattleGroundMgr.cpp#L1052
Rank display in score (character Orcadmin has HW rank):
Pre fix (look at icon): https://cdn.discordapp.com/attachments/788137519665381407/836902020198825984/unknown.png
Post fix: https://cdn.discordapp.com/attachments/788137519665381407/836932710886277130/u …
=> Fix BG score list & queue update

src/game/Chat/Level2.cpp
Fix tables junctions in the methods HandleLookupAccountEmailCommand, HandleLookupAccountNameCommand, HandleLookupPlayerIpCommand.
That seems be enough clear for bypass an book story for desc.
That can fix the error "Column 'id' in field list is ambiguous" too.
See you soon cMangos
- None
- None
- None
=> Update refs between junctions tables in Level2.cpp

src/game/Entities/GameObject.h
Backport from tbc, fixes BG traps and maybe something else
- Fixes GO ground collision that makes GO like BG Buffs (TYPE_TRAP) not find targets.
Enter WSG and try any buff
Affects all GOs, but I took it from tbc core so I guess is safe
=> Fix GO collision height

src/game/Mails/MailHandler.cpp
In Classic, mails sent between characters of your account should not be instant, but still subject to the one-hour delay.
The "instant mail within the same account" change was introduced in 2.1.3 as an undocumented change.
- https://wowpedia.fandom.com/wiki/Patch_2.1.3
> Any mail between characters on the same account is now instant regardless of money or items attached.
- None
- Create two characters, log into one, send the other an item via mail, log into the other character and check your mailbox.
=> Mails sent to characters within the same account are subject to the same one-hour delay in Classic

src/game/Entities/Pet.cpp
Currently, Warlock pets are subjected to multiplier values in creature_template. This makes them have less or more hp/mana/armor than intended, because those values should not be used for player-controlled pets.
- None
- Fixes [#2756](https://github.com/cmangos/issues/issues/2756)
- Create a Warlock, level it up to 60.
- Summon Warlock pets one by one and check them against the values in pet_levelstats.
=> Fix health/mana/armor stat calculation for Warlock pets

src/game/Spells/SpellMgr.h
[Lunar Fortune](https://classic.wowhead.com/spell=26522/lunar-fortune) should not stack with itself. Depending on luck (you have a 50% chance of obtaining this item from the mail you receive when you do the Elder quests during the Lunar Festival) you could get 30+ of those items, giving a 7500 increase of hp if it was allowed to stack.
Tested on TBC PTR, it does not stack when using two of those.
- None
- .event start 7
- .add 21744 2
- .go obj id 180859
- Use the two Lucky Rocket Clusters.
=> Spell: prevent Lunar Fortune from stacking with itself

src/game/Spells/Spell.cpp
On Classic and Classic only, trying to summon a Warlock demon while you already have one summoned will force the current one to despawn as soon as you start casting the new demon's summoning spell.
Added this check here in Spell::CheckCast() instead of Spell::prepare() because there's already code handling pets in the former, and TC handles the Summoning Disorientation stun in there too.
- None
- Fixes https://github.com/cmangos/issues/issues/2762
- Create a Warlock.
- Summon a pet.
- Try to summon another pet.
=> Unsummon active Warlock demons when trying to summon a new one

src/game/MotionGenerators/MotionMaster.cpp
The MotionMaster::MovePoint() version used by SCRIPT_COMMAND_MOVE_DYNAMIC did not send guid and relayId to PointMovementGenerator.
=> Fix SCRIPT_COMMAND_MOVE_DYNAMIC not using specified relayId (dataint2)

src/game/Entities/Creature.cpp
Using .npc add to spawn a NPC gives a console error about the insert query failing to execute, and the spawned NPC would not be saved in the database. The generated logSQL file would not work when running it, either.
This is because spawnMask is an uint8, which in C++ is a character type and interpreted as such. So the query would be executed with an invalid character instead of the spawnMask integer, and fail to run.
Also converted the two nearby C-style casts to static_casts as I noticed those are preferred for newer code, sorry if I did wrong.
- .npc add 1
- Check console output and logSQL file created in server dir.
=> Fix saving of NPCs spawned via .npc add command to DB

src/game/BattleGround/BattleGroundAB.cpp, src/game/BattleGround/BattleGroundAB.h
Disables graveyards inside bases (where you spawn on teleporting into bg) after BG starts. Players who die near base or if all bases are captured by enemy should teleport to the graveyard to the side of the base, where Spirit Healer is. (Without fix closest GY is in most cases = inside base, which is not correct).
=> Disable AB graveyards inside bases during BG

src/shared/Log.cpp, src/shared/Util.cpp
Fix log file timestamps the same way vmap extraction was fixed in https://github.com/cmangos/mangos-classic/commit/b5baa9f8931f9751928de5e3ace70cd9c7a6c447.
- None
- Closes https://github.com/cmangos/issues/issues/2778.
- Set LogTimestamp = 1 in realmd.conf, start realmd.exe, check created log's file name.
=> Fix log file timestamps

src/game/Entities/Creature.cpp, src/game/Entities/Unit.cpp
This is something I noticed while testing other things, but the sniffer and parser aren't updated yet so I had to get a bit creative. Please bear with me.
This PR fixes two bugs:
- When you start attacking a mob while close to it (so that no attack errors like "out of range" are triggered) and for creatures, the off hand attack is delayed by half its own attack speed, not by the full attack speed.
- Mobs do not do off hand attacks 1/4 faster than main hand attacks.
I needed a way to measure it as precisely as possible. Enter 120 fps videos and [Avidemux](http://avidemux.sourceforge.net/) (video player that shows the frame time in milliseconds).
First example: 2.4 speed MH, 2.5 speed OH
https://user-images.githubusercontent.com/99603810/156881720-ef253838-9575-45e2-a859-9de2aee8bb3e.mp4 …
=> Set off-hand attack speed for mobs to the same speed as main hand, and delay off-hand attack by half of the speed instead of the full speed

src/game/World/WorldState.cpp, src/game/World/WorldState.h
Fixes Scourge invasion letters being sent on every server start
- Event mail with quest item is sent on every server start if scourge invasion is enabled. E.g. start server 30 times = get 30 letters to every character.
- Start Scourge Invasion (.worldstate scourge state 1), you receive 1 letter with quest item, restart server. You now have 2 identical letters (only first one will have item though).
=> Fix Scourge Invasion mail spam

sql/base/mangos.sql
Fix error below on mangos.sql import
ERROR 1136 (21S01) at line 325: Column count doesn't match value count at row 1
- None
- None
- None
=> Fix mangos.sql import error

src/game/Groups/GroupHandler.cpp
Fixes ready check handler
Taken from vmangos
Original code is from tbc, in 1.12 it should not have player guid who started it sent on request (Because client automatically shows leader name in request, Assistants cant do ready check as in tbc), and response from players should only be sent to raid leader, otherwise leader sees that he is not ready and other artifacts.
- Make a raid of 2+ ppl
- Try to do ready check
- Watch result
=> Fix ready check

src/game/BattleGround/BattleGroundWS.cpp
This PR fixes the WSG flag being uncapturable if the own flag of capturing team was just recaptured from enemy players and respawned at base.
Also fixes a UI issue that causes the flag of the wrong team to disappear in the HUD.
- .debug bg
- Queue for Warsong
- Pick up flags from both bases, drop the flag of the horde player and let the alliance player return the flag back to base by right-clicking, then try to capture the horde flag with the alliance player.
This issue should affect all 3 versions, so the fix would have to  be ported to all 3 versions.
=> Fix uncappable flag in WSG & UI bugs

src/game/Maps/SpawnGroup.cpp
fix segmentation fault caused by multithread access m_objects in CreatureGroup::Despawn
I found my mangosd crashes every day at 12:00 a.m. After added some log I found these lines of code called simultaneously.
```
void SpawnGroup::RemoveObject(WorldObject* wo)
{
m_objects.erase(wo->GetDbGuid());
// ...
}
void CreatureGroup::Despawn(uint32 timeMSToDespawn, bool onlyAlive, uint32 forcedDespawnTime)
{
//...
for (auto objItr : m_objects)   // segmentation fault here
{
}
}
```
- None
=> fix multithread access segmentation fault

src/game/MotionGenerators/PathFinder.cpp, src/game/MotionGenerators/PathFinder.h
This pull request fixes the pathfinders ability to actually use previously saved polyRefs and stops the same from being saved over and over.
An issue was found by looking for memory leaks. For a server that was running for multiple hours Pathfinder.m_pathPolyRefs https://github.com/cmangos/mangos-classic/blob/1debc9cd703d5372ceb5fcb4f279cd8d2b907895/src/game/MotionGenerators/PathFinder.h#L102
was filled with many duplicate records. Futher inspection showed these duplicate records are not used.
This issue is introduced in (https://github.com/cmangos/mangos-classic/commit/9c0a31b496977ad55d11dc7753579a17ae29f93c) and probably the result of an imcomplete change.
This PR fixes the issue where saved polyRefs are not properly found for later use. This also attempts to prevent the same polyRef …
=> Pathfinder memory leak fix and actually use saved polyRefs.

src/game/Spells/SpellAuras.cpp
This PR moves Spell Mod Auras out of the packet handlers and into the Aura Effect-Value calculation.
- fixes https://github.com/cmangos/issues/issues/3032
(Was already fixed for TBC and WotLK, but works differently in vanilla)
- Create a mage
- level mage to 60
- learn spell Blizzard
- spec 3 points into Permafrost
- spec 3 points into Improved Blizzard
- watch as the "Chilled" debuff no longer falls off when channeling continuously
=> Spells: Move SpellMods out of Handlers

src/game/Spells/SpellEffects.cpp
It's already generated and set as the entry of the ObjectGuid in CreateBaseAtCreature
vmangos had same issue https://github.com/vmangos/core/commit/b1e49ba3e6043a21416480b03bd3ff74f60e441f
=> Don't generate pet number twice on tame.

src/game/Entities/Item.cpp
This pull request attempts to prevent undeeded database calls while players are logging in. 
During loading of item_instance from db Item::LoadFromDB a check is done to fix max durability and durability here:
https://github.com/cmangos/mangos-classic/blob/5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Item.cpp#L448
However the durability is correctly filled here:
https://github.com/cmangos/mangos-classic/blob/5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Item.cpp#L467
and fixed to be lower than maxDurability here:
https://github.com/cmangos/mangos-classic/blob/5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Item.cpp#L473
Because GetUInt32Value(ITEM_FIELD_MAXDURABILITY) is empty at the moment of the first check need_save will always be true and an update …
=> Prevent unneeded item_instance update when loading from db.

src/game/AI/ScriptDevAI/scripts/kalimdor/razorfen_downs/razorfen_downs.cpp
Fix the random selection of spawn position for the escort quest in Razorfen Downs, the random generates a value between 1 and 3, but the array has indexes from 0 to 2.
- Crashdump: https://pastebin.com/Texv5JNB
- Access an out of bounds coordinate due to bad random number generated.
- Go to Razorfen Downs and look for the NPC belnistrasz (Entry: 8516) and start the escort quest (Entry: 3525). Because of the randomness of it you have 1/3 chance of reproducing the issue and access an out of bounds value of the array.
=> Fix Razorfen Downs Escort Quest

src/game/Entities/Camera.cpp
This PR activates the **UpdateVisibilityForOwner** handling for playerbots. Deactivation led to the playerbot grid not loading in special cases (presumably resurrection).
https://discord.com/channels/362206349339262976/1223715932468412446
=> Playerbots: Fix grid loading issue

src/game/Entities/PetitionsHandler.cpp
Fixes packet structure for SMSG_PETITION_QUERY_RESPONSE. The added integer field is maybe also missing in cmangos-tbc and cmangos-wotlk.
Co-authored-by: GrenderG <grenderg@gmail.com>
https://github.com/vmangos/core/commit/b9b006db08fcdc055057ff68a3f9fe295ead3ba5 https://github.com/vmangos/core/commit/e349565acb8a358aa021fa0b23090f4626fd72d3
=> Core/PacketIO: Correct and add field names for SMSG_PETITION_QUERY_RESPONSE

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/molten_core/boss_magmadar.cpp
I have noticed Magmadar boss in Molten Core (Entry:  11982) uses the Panic ability (Spell: 19408) too often. Upon further research I've noticed the cooldowns are not blizzlike as they should be between 30-36 seconds between casts.
- Wowhead comment in 2006: https://www.wowhead.com/classic/npc=11982/magmadar#comments:id=85
- Vmangos: https://github.com/vmangos/core/blob/a8ca7e1d4e35f0b5ac3e3a1f840eb42c57999470/src/scripts/eastern_kingdoms/burning_steppes/molten_core/boss_magmadar.cpp#L96
- Video: https://youtu.be/RXdhDeVfH9k?si=TVV45O4vaVAsjBhv&t=338 Fear casted at 5:53 and then at 6:27
Go to magmadar in molten core or summon him with .npc add 11982 and count the amount of seconds between each fear.
=> Magmadar panic should have a higher cooldown

src/game/Entities/Player.cpp
Added "IsTrivialLevelDifference" to grant honor when the victim has green, yellow or red name.
According to blizzards wow website in 2005 (waybackmachine) honor is granted when the name is green, yellow or red.
"Honorable Kill: killing a player character within your XP range, i.e. a character whose name is colored (green to red), not grey. [...]"
source: https://web.archive.org/web/20050619021442/http://www.worldofwarcraft.com/pvp/honorguide.html
the old calculation would only grant honor on pvp-kill if the player was max. 5 level below the killer's level, even if the name is still green.
"Honorable Kill: killing a player character within your XP range, i.e. a character whose name is colored (green to red), not grey."
https://web.archive.org/web/20050619021442/http://www.worldofwarcraft.co …
=> Granting honor on PvP-Kill blizzlike

src/game/Spells/Spell.cpp
Players should be able to lockpick other players items that are placed in the trade window
- vmangos: https://github.com/vmangos/core/blob/f53de3d5b43d1654f02e7ee2c8e3f6b5e1f5c907/src/game/Spells/Spell.cpp#L6642
- wowiki: [Patch 1.2.2](https://wowpedia.fandom.com/wiki/Patch_1.2.2) (2005-02-15): Rogues now correctly gain Lockpicking skill from items picked in the trade window. https://wowpedia.fandom.com/wiki/Pick_Lock
- Log in with two clients
- Learn lockpicking skill with one of them (.learn 1809)
- Get the thieve tools (.additem 5060)
- Get a locked box with the other character (.additem 6712)
- Trade the locked box (place it in the will not trade slot)
- Cast the lockpick spell and press trade
=> Allow lockpicking items in the trade window

src/game/AI/ScriptDevAI/scripts/kalimdor/temple_of_ahnqiraj/boss_cthun.cpp
Fix cthun resetting on second phase after tentacles despawn
https://github.com/cmangos/issues/issues/3391
- Go to cthun and .die the eye
- Fight the second phase for a bit
- See that it doesn't reset after a while
=> Fix cthun resetting on second phase after tentacles despawn

src/game/Entities/Player.h
Updates raid group error definitions for SMSG_RAID_GROUP_ONLY (1.12. and 2.4.3 only). Verified using IDA.
=> Core/PacketIO: Update RaidGroupError enum

src/game/Server/WorldSession.h
Remove unimplemented method declarations from WorldSession
=> WorldSession: Remove unimplemented method declarations

src/game/Entities/GossipDef.cpp
Updates the packet structure for SMSG_QUESTGIVER_REQUEST_ITEMS.
After the loop, all three clients (1.12.2, 2.4.3, and 3.3.5) read only these four flags/booleans and combine them with && into a boolean value (probably 'Completable' according to the original comment - // Completable = flags1 && flags2 && flags3 && flags4). The four flags are neither stored nor any further processed (1.12.2, 2.4.3, and 3.3.5). Verified using IDA.
=> Core/PacketIO: Update SMSG_QUESTGIVER_REQUEST_ITEMS

src/game/Maps/Map.cpp
disable map optimizations for playerbots if sPlayerbotAIConfig.DisableBotOptimizations (default off - optimizations enabled) to allow full activity at all times
because no other way to disable this behavior from config, and it hinders bot activity
- build with Playerbots
- set AiPlayerbot.DisableBotOptimizations = 1 in aiplayerbot.conf
- launch the server
=> disable map optimizations for playerbots if sPlayerbotAIConfig.DisableBotOptimizations

src/game/AI/ScriptDevAI/scripts/kalimdor/ruins_of_ahnqiraj/boss_moam.cpp, src/game/AI/ScriptDevAI/scripts/kalimdor/temple_of_ahnqiraj/boss_ouro.cpp
SELECT id,auras FROM ccsdb_v3.creature WHERE id IN (15340,15517);
SELECT * FROM ccsdb_v3.creature_spell_timers WHERE spell_id IN (18941) ORDER BY entry,spell_id;
=> [SD] Moam and Ouro use Double Attack manually

src/game/BattleGround/BattleGround.cpp
This PR removes one of prepared statement placeholders for the Battleground scoreboard insert. Running the statement otherwise will run into an assertion.
=> BG: Fix prepared statement having too many placeholders

src/game/Entities/Player.cpp
This PR fixes players with true-Rank 6 (visualRank 2) being able to enter the officers hall
=> PvP: Fix required rank for officer hall

src/game/World/World.h, src/realmd/AuthSocket.cpp, src/realmd/RealmList.cpp, src/realmd/RealmList.h, src/shared/Common.h
The current configuration option for realm categories via the "RealmZone" option in cmangos-classic is causing issues. In version 1.12, only a maximum of four realm categories (1, 2, 3, 5) per locale/region exist. If a different value, such as 12 (RealmZone: Russian, Cyrillic), is used to set the cyrillic character set, the realm will not appear on the clients realm list. This limitation prevents consistent assignment of a valid realm category alongside the desired character set.
~~This PR implements a configuration option for realm categories (defined in Cfg_Categories.dbc) that is independent of the character set setting of "RealmZone".~~
Unlike TBC and WotLK, the categories are not uniquely numbered in 1.12; instead, some entries use the same ID for multiple entries. In cmangos-tbc and …
=> Realm/Core: Implement realm category mapping using realm zone and major version

src/game/Entities/Player.cpp
This is a small PR to allow compilation with the enable_playerbots flag active with the new weakptr system for quests.
The same solution is used here as in the rest of the bot-codebase at the moment.
See also https://github.com/cmangos/mangos-tbc/pull/708
=> Playerbot: Compile fix for new quest weakptr

src/game/Server/WorldSocket.cpp, src/game/Server/WorldSocket.h, src/mangosd/Master.cpp, src/mangosd/Master.h, src/mangosd/RASocket.cpp, src/mangosd/RASocket.h, src/realmd/AuthSocket.cpp, src/realmd/AuthSocket.h, src/realmd/Main.cpp, src/shared/Metric/Metric.cpp, src/shared/Metric/Metric.h, src/shared/Network/AsyncListener.hpp, src/shared/Network/AsyncSocket.hpp, src/shared/Util/Util.cpp
This PR enables the use of Boost 1.87
=> Boost: Migrate deprecated components to 1.87

src/game/Spells/SpellEffects.cpp
This PR fixes the pet not losing happiness when it's being dismissed
- Tame pet
- Feed pet to 100k Happiness points (check with `.debug listupdatefields` )
- Keep dismissing and calling the pet on repeat
- With fix pet will become unhappy after ~40 seconds
- without fix pet will become unhappy after 5 minutes (normal happiness countdown)
=> Pet: Fix pet not losing happiness when dismissed

dep/g3dlite/System.cpp
This change allows for compilation under RISC-V instruction set CPU's. Tested functionality of server, could enter game, playerbots compiles, all extractors work.
- None
- When compiling on a RISC-V CPU would error out in build due to undefined processor definition causing to to fall back to x86 code.
- Attempt to build on RISC-V
- Error
- Apply change, error gone and compile successful
=> G3D: Add support for RISC-V CPU's

src/game/AuctionHouseBot/AuctionHouseBot.cpp, src/game/AuctionHouseBot/AuctionHouseBot.h, src/game/AuctionHouseBot/ahbot.conf.dist.in
This feature adds support for filtering items listed by AuctionHouseBot using either a **static** or **dynamic** RequiredLevel cap.
- **Static filtering** uses a fixed value from the config
- **Dynamic filtering** adjusts based on the highest-level online character(s), with optional exclusion of GM accounts
This controls both the maximum RequiredLevel and ItemLevel allowed in auction listings, helping tailor AHBot behavior to the server’s progression.
---
- If `AuctionHouseBot.Level.DynamicMaxRequired = 1`, RequiredLevel is capped using the result of:
`SELECT MAX(level) FROM characters WHERE online = 1`
- If disabled (`= 0`), the static config value `AuctionHouseBot.Level.MaxRequired` is used instead
- If `AuctionHouseBot.Level.IgnoreGmAccounts = 1`, GM accounts are excluded from dynamic …
=> AHBot: Add support for dynamic or static filtering by RequiredLevel and ItemLevel

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-release.yml, .github/workflows/windows.yml, cmake/macros/FindMySQL.cmake
Ubuntu 20.04 runners will soon be shut down by GH. Some of the Discord notifiers were still using this version. Also since there is only 1 remaining x64 Apple runner, upgraded the Apple CI test to be compatible with Apple Silicon.
(https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)
- None
- None
=> Upgrade soon to be deprecated runners to newer versions
