sql/base/mangos.sql
ERROR 1136 (21S01) at line 1264: Column count doesn't match value count at row 1 will be fixed
=> fix sql insert statement for creature_template

src/game/Object.h, src/game/Spell.cpp, src/game/Spell.h, src/game/ThreatManager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cmangos/mangos-classic/158)
=> Crash fixes

src/game/Spell.cpp
By @Caydan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cmangos/mangos-classic/180)
=> Game/Spell: Handle SPELL_FAILED_NOTHING_TO_DISPEL

src/realmd/CMakeLists.txt
Help cmake find OpenSSL on Mac
=> Fix OpenSSL include path on Mac

src/game/Player.cpp, src/game/Player.h
If you wanna see the issue I'm talking about then;
https://github.com/cmangos/issues/issues/1045#issuecomment-242015294
1. Make an alliance char
2. `.level 59`
3. `.tele chillwind`
4. complete Argent Dawn Commission.
=> Fix quest rewards appearing twice in chat

dep/include/g3dlite/G3D/System.h
=> Fix FreeBSD build

src/game/LootHandler.cpp
=> Interrupt cast at looting

src/scriptdev2/scripts/eastern_kingdoms/molten_core/boss_lucifron.cpp
+ update some timers
+ Shadow Shock should hit the current victim only
=> Molten Core - Lucifron

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/blackwing_lair/boss_chromaggus.cpp, src/game/Spells/SpellEffects.cpp
allow more creatures than just Chromaggus to use Elemental Shields & Broodpowers
(e.g. Death Talon Wyrmguard, Death Talon Overseer)
=> BWL - Elemental Shield / Broodpower

src/game/Globals/ObjectMgr.cpp
Use GetOrNewIndexForLocale to get correct locale index
=> Fix questgiver greeting locales loading

src/game/AI/ScriptDevAI/ScriptDevAIMgr.h
https://github.com/cmangos/issues/issues/1613
=> fix uninitialized pointer

src/game/AI/ScriptDevAI/scripts/kalimdor/dire_maul/dire_maul.h, src/game/AI/ScriptDevAI/scripts/kalimdor/dire_maul/instance_dire_maul.cpp, src/game/Maps/InstanceData.h
Stomper Kreeg and Cho'rush the Observer pay tribute as well.
see https://github.com/cmangos/classic-db/issues/130#issuecomment-394048171 for more information
=> Dire Maul North Tribute

src/game/Entities/CharacterHandler.cpp, src/game/Globals/ObjectMgr.cpp, src/game/Groups/Group.cpp, src/game/Guilds/Guild.cpp, src/game/Guilds/GuildMgr.cpp, src/game/Spells/SpellMgr.cpp
rank is now a keyword. groups is also a keyword.
This has full backwards compatibility with older versions of SQL
I had already made this for classic so I'm gonna PR it as well 'cause why not.
=> SQL 8 (MySQL 8.0) compliance

src/game/Spells/Spell.cpp
Fixes https://github.com/cmangos/issues/issues/1901.
=> Unsummon demon immediately when summoning another one.

.github/PULL_REQUEST_TEMPLATE.md, .gitignore
Github PR Template - agreed upon in the issues Repo. Modified gitignore to include .github/ folder.
- https://github.com/cmangos/issues/pull/1928
- relates https://github.com/cmangos/issues/pull/1928
- Merge and make new PR (merge is required)
=> 🍰 Github PR Template

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/shadowfang_keep/shadowfang_keep.cpp
=> Attempt to fix GCC build

src/mangosd/mangosd.conf.dist.in
=> resolve merge conflict in mangosd.conf.dist.in

src/game/Mails/MailHandler.cpp
carbon copy of [d154093bdee70a919670005f87e9322e564a118a](https://github.com/cmangos/mangos-tbc/commit/d154093bdee70a919670005f87e9322e564a118a) by killerwife
fixes https://github.com/cmangos/issues/issues/2569
=> Fix missing money modification on mail send due to anticheat commit

src/game/Grids/GridNotifiers.cpp, src/game/Maps/SpawnManager.cpp, src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp, src/game/World/WorldStateVariableManager.h
Somehow some hearders are not include or not in the right order by some compilers.
See https://github.com/cmangos/issues/issues/2580
=> Fixes for issue https://github.com/cmangos/issues/issues/2580

src/game/Entities/Unit.cpp, src/game/Entities/Unit.h, src/game/Spells/SpellAuras.cpp
Fixes aura with ModEffectImmunity remove itself on apply
Fixes WSG flag aura removing itself on apply
Enter WSG and try to pick up enemy flag
Not sure how it affects other auras
=> Fix Aura with ModEffectImmunity self remove

src/game/Entities/GameObject.cpp
Forgot to fix gameobjects too in https://github.com/cmangos/mangos-classic/pull/476.
- None
- None
- None
=>  Fix saving of gameobjects spawned via .gobj add command to DB

src/game/Entities/Unit.cpp, src/game/Groups/Group.h, src/game/Groups/GroupHandler.cpp
Fixes group update flags being a copy paste from tbc
Also fixes debuffs in party/raid default UI in 1.12
I did it because I can't use Hermes Proxy + 1.14 otherwise
=> Port group update flags from vmangos

src/game/Entities/DynamicObject.h
Port from tbc/wotlk
Fixes almost non working aoe like blizzard etc
- AoE spells (blizzard, consecration or any other) do not work most of the time
- Use any AoE spell on enemies
=> Fix dynamic object ground collision

src/game/Entities/NPCHandler.cpp
Fixes wrong change in 6518d361025ef904c2f88e8757c61c8a423566c8, Thanks Shauren
=> Fix wrong change in trainer spells commit

src/game/Spells/Spell.cpp
Adds missing break;
In wotlk is present
=> missing break in Spell.cpp

src/game/AI/ScriptDevAI/base/TimerAI.cpp
Timer ID and Timer are missing in output string
- None
- None
- None
=> Remove suspicious comma

src/game/AI/ScriptDevAI/scripts/kalimdor/desolace.cpp, src/game/PlayerBot/Base/PlayerbotAI.cpp, src/game/PlayerBot/Base/PlayerbotMgr.cpp
Check pointers before usage
- None
- None
- None
=> Null pointers check

src/game/Server/Opcodes.cpp
The table should now be complete. There are exactly 828 entries.
=> Network: Add missing opcodes to opcode table

src/game/Chat/ChatHandler.cpp, src/game/Entities/Player.h
Update essential to playerbot changes
=> bot iteration and cleanup

src/game/Entities/MiscHandler.cpp
Fixes the packet structure for SMSG_LOGOUT_COMPLETE.
=> Core/PacketIO: Update SMSG_LOGOUT_RESPONSE

src/game/Entities/Player.cpp, src/game/Server/WorldSession.cpp, src/game/Server/WorldSession.h
Fixes the packet structure for SMSG_TRANSFER_ABORTED (1.12. only).
=> Core/PacketIO: Fix SMSG_TRANSFER_ABORTED

src/game/Chat/debugcmds.cpp, src/game/Entities/Player.cpp, src/game/Entities/Player.h, src/game/Quests/QuestHandler.cpp
Fixes the packet structure for MSG_QUEST_PUSH_RESULT (all cores).
Co-authored-by: brotalnia brotalnia@gmail.com
=> Core/PacketIO: Update MSG_QUEST_PUSH_RESULT

src/game/Entities/QueryHandler.cpp
Small cleanup for SMSG_GAMEOBJECT_QUERY_RESPONSE (1.12. only). Verified using IDA.
=> Core/PacketIO: Update SMSG_GAMEOBJECT_QUERY_RESPONSE

src/game/Entities/PetHandler.cpp, src/game/Server/WorldSession.h
Update packet structure for SMSG_PET_NAME_INVALID (1.12. only). Verified using IDA.
=> Core/PacketIO: Update SMSG_PET_NAME_INVALID

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_renataki.cpp
This PR fixes Renataki's Blade-Dance basically calling its own spell script in an infinite loop.
- None
- discussed in Discord
- Do the Renataki encounter.
=> Fix Renataki Blade Dance

src/game/BattleGround/BattleGroundHandler.cpp, src/game/BattleGround/BattleGroundMgr.cpp, src/game/BattleGround/BattleGroundMgr.h
Fixes the packet structure for SMSG_GROUP_JOINED_BATTLEGROUND (1.12. only). Verified using IDA.
=> Core/PacketIO: Fix SMSG_GROUP_JOINED_BATTLEGROUND

src/game/Entities/Player.h
Remove unused method declaration: Item* BankItem(uint16 pos, Item* pItem, bool update); in Player class
=> Player: Remove unimplemented method declaration for BankItem

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/blackwing_lair/boss_razorgore.cpp
Make Razorgore Vanilla Blizzlike
https://github.com/cmangos/issues/issues/3714
=> make razorgore vanilla blizzlike

src/game/World/World.cpp
This PR fixes the new AHBot not being initialized.
=> Playerbot: Fix new AHbot not being initialized
